[0m14:02:47.487754 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001981C15BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001981E337D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001981E337890>]}


============================== 14:02:47.493882 | 955dce4b-ddc9-4a29-9954-1688aa914dc1 ==============================
[0m14:02:47.493882 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:02:47.494884 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init ethio_med_dwh', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:02:47.535515 [debug] [MainThread]: Starter project path: C:\Users\hp\Desktop\10 academy\ethio_medical_dw\venv\Lib\site-packages\dbt\include\starter_project
[0m14:02:47.582543 [info ] [MainThread]: 
Your new dbt project "ethio_med_dwh" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:02:47.584118 [info ] [MainThread]: Setting up your profile.
[0m14:03:58.407005 [info ] [MainThread]: Profile ethio_med_dwh written to C:\Users\hp\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:03:58.409312 [debug] [MainThread]: Command `dbt init` succeeded at 14:03:58.409034 after 71.16 seconds
[0m14:03:58.409819 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001981E393BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001981E5E8170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001981D206250>]}
[0m14:03:58.410398 [debug] [MainThread]: Flushing usage events
[0m14:03:59.469754 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:08:26.062810 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022E28C97E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022E2AE77D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022E2AE77890>]}


============================== 14:08:26.068751 | 22f98f65-e818-41c6-a66c-cbd050d83241 ==============================
[0m14:08:26.068751 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:08:26.069872 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:08:26.114143 [info ] [MainThread]: dbt version: 1.10.4
[0m14:08:26.115189 [info ] [MainThread]: python version: 3.13.1
[0m14:08:26.116323 [info ] [MainThread]: python path: C:\Users\hp\Desktop\10 academy\ethio_medical_dw\venv\Scripts\python.exe
[0m14:08:26.117973 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:08:26.254376 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m14:08:26.256230 [info ] [MainThread]: Using profiles dir at C:\Users\hp\.dbt
[0m14:08:26.257112 [info ] [MainThread]: Using profiles.yml file at C:\Users\hp\.dbt\profiles.yml
[0m14:08:26.257957 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml
[0m14:08:26.258942 [info ] [MainThread]: Configuration:
[0m14:08:26.260081 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m14:08:26.261624 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:08:26.262888 [info ] [MainThread]: Required dependencies:
[0m14:08:26.264418 [debug] [MainThread]: Executing "git --help"
[0m14:08:26.328394 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m14:08:26.328947 [debug] [MainThread]: STDERR: "b''"
[0m14:08:26.329437 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m14:08:26.330122 [info ] [MainThread]: Connection test skipped since no profile was found
[0m14:08:26.330840 [info ] [MainThread]: [31m2 checks failed:[0m
[0m14:08:26.331566 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "jaffle_shop", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!


[0m14:08:26.332185 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml> not found

[0m14:08:26.333254 [debug] [MainThread]: Command `dbt debug` failed at 14:08:26.333087 after 0.44 seconds
[0m14:08:26.333785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022E2B1189D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022E2B10E330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022E2AF55F20>]}
[0m14:08:26.334192 [debug] [MainThread]: Flushing usage events
[0m14:08:28.286328 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:18:18.156063 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACBF13FE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACC035BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACC035B890>]}


============================== 02:18:18.171567 | ccffaec9-47fd-4f71-a3bc-f504b4a754c8 ==============================
[0m02:18:18.171567 [info ] [MainThread]: Running with dbt=1.10.4
[0m02:18:18.174250 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:18:18.176062 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:18:18.178963 [debug] [MainThread]: Command `dbt run` failed at 02:18:18.178564 after 0.23 seconds
[0m02:18:18.180107 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACC03AC2B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACC03B8710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACC01E5480>]}
[0m02:18:18.181401 [debug] [MainThread]: Flushing usage events
[0m02:18:19.126642 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:18:43.779614 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000229850EBE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000229872DBD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000229872DB890>]}


============================== 02:18:43.785027 | a334ad55-1ca9-4179-b456-70a90311d2b8 ==============================
[0m02:18:43.785027 [info ] [MainThread]: Running with dbt=1.10.4
[0m02:18:43.785809 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:18:43.786323 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:18:43.787718 [debug] [MainThread]: Command `dbt run` failed at 02:18:43.787544 after 0.16 seconds
[0m02:18:43.788247 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002298732C2B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022987338710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022986195480>]}
[0m02:18:43.788795 [debug] [MainThread]: Flushing usage events
[0m02:18:44.636907 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:19:01.309686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A06793BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A069B2BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A069B2B890>]}


============================== 02:19:01.319679 | 4c7777d8-2b14-48af-b24e-9f3236506a70 ==============================
[0m02:19:01.319679 [info ] [MainThread]: Running with dbt=1.10.4
[0m02:19:01.321255 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m02:19:01.322491 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:19:01.325597 [debug] [MainThread]: Command `dbt run` failed at 02:19:01.325205 after 0.31 seconds
[0m02:19:01.326464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A069B7C2B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A069B88710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A0689E5480>]}
[0m02:19:01.327340 [debug] [MainThread]: Flushing usage events
[0m02:19:02.019846 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:20:28.263727 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E0FA9BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E11C8BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E11C8B890>]}


============================== 02:20:28.270075 | e0895937-d08e-4cf6-963e-7fcb7b3540a8 ==============================
[0m02:20:28.270075 [info ] [MainThread]: Running with dbt=1.10.4
[0m02:20:28.270773 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m02:20:28.271243 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:20:28.272707 [debug] [MainThread]: Command `dbt run` failed at 02:20:28.272576 after 0.17 seconds
[0m02:20:28.273058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E11CDC2B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E11CE8710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E10B45480>]}
[0m02:20:28.273416 [debug] [MainThread]: Flushing usage events
[0m02:20:29.073004 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:22:46.107510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268D665BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268D884BD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268D884B890>]}


============================== 02:22:46.113833 | e13207dc-8e4d-425c-a2a4-06d6c836a053 ==============================
[0m02:22:46.113833 [info ] [MainThread]: Running with dbt=1.10.4
[0m02:22:46.114772 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m02:22:46.115313 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\10 academy\ethio_medical_dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:22:46.116438 [debug] [MainThread]: Command `dbt run` failed at 02:22:46.116290 after 0.23 seconds
[0m02:22:46.116866 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268D889C2B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268D88A8710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268D7705480>]}
[0m02:22:46.117274 [debug] [MainThread]: Flushing usage events
[0m02:22:46.919370 [debug] [MainThread]: An error was encountered while trying to flush usage events
